"""generate_portfolio.py.

Synthetic portfolio generator for the Basel III credit scoring engine.

Produces:
    - counterparties_data.sql        (~1 500 counterparties)
    - contracts_data.sql             (5 000 leasing contracts)
    - collaterals_data.sql           (one collateral row per contract)
    - regulatory_parameters_data.sql (CRR2 standard-approach seed)

All amounts are expressed in EUR, percentages are stored as decimals
(0.75 = 75%). Random seed is fixed to 42 for reproducibility.

Author : Tristan Mas | github.com/tristan-mas
Version: 1.0 | 2025
"""

from __future__ import annotations

import logging
import os
from dataclasses import dataclass
from datetime import date, timedelta
from typing import Iterable

import numpy as np
import pandas as pd
from faker import Faker

# --------------------------------------------------------------------------- #
# Configuration                                                                #
# --------------------------------------------------------------------------- #

SEED = 42
NB_COUNTERPARTIES = 1500
NB_CONTRACTS = 5000

OUTPUT_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "data")

COUNTERPARTY_TYPE_MIX = {
    "RETAIL": 0.40,
    "SME": 0.40,
    "CORPORATE": 0.20,
}

RATING_MIX = {
    "AAA": 0.05,
    "AA":  0.05,
    "A":   0.20,
    "BBB": 0.30,
    "BB":  0.20,
    "B":   0.12,
    "CCC": 0.05,
    "D":   0.03,
}

COUNTRY_MIX = {
    "FRA": 0.35,
    "DEU": 0.20,
    "ESP": 0.15,
    "ITA": 0.15,
    "BEL": 0.08,
    "NLD": 0.07,
}

SECTOR_CODES = ["A", "C", "F", "G", "H", "I", "J", "K", "L", "M"]

PRODUCT_TYPE_MIX = {
    "OPERATING_LEASE": 0.55,
    "FINANCE_LEASE":   0.45,
}

ASSET_CLASS_MIX = {
    "PASSENGER_CAR": 0.55,
    "LCV":           0.20,
    "TRUCK":         0.15,
    "EQUIPMENT":     0.10,
}

COLLATERAL_TYPE_PROB = {
    "VEHICLE":     0.75,
    "REAL_ESTATE": 0.05,
    "GUARANTEE":   0.10,
    "NONE":        0.10,
}

DEFAULT_HAIRCUTS = {
    "VEHICLE":     0.20,
    "REAL_ESTATE": 0.10,
    "GUARANTEE":   0.15,
    "NONE":        0.00,
}

# Outstanding balance ranges (log-normal): (mean_log, sigma_log) producing
# values inside the brief's bracket.
BALANCE_PARAMS = {
    "RETAIL":    {"mu": np.log(15_000),  "sigma": 0.6, "low":   5_000, "high":    50_000},
    "SME":       {"mu": np.log(80_000),  "sigma": 0.9, "low":  20_000, "high":   500_000},
    "CORPORATE": {"mu": np.log(700_000), "sigma": 1.0, "low": 100_000, "high": 5_000_000},
}

TURNOVER_PARAMS = {
    "RETAIL":    None,  # not applicable
    "SME":       {"mu": np.log(10_000_000),  "sigma": 0.8},
    "CORPORATE": {"mu": np.log(200_000_000), "sigma": 1.0},
}

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s | %(levelname)-7s | %(message)s",
)
logger = logging.getLogger("portfolio")


# --------------------------------------------------------------------------- #
# Helpers                                                                      #
# --------------------------------------------------------------------------- #

@dataclass
class GeneratorContext:
    """Holds the shared RNG and faker instances."""

    rng: np.random.Generator
    fake: Faker


def _weighted_choice(rng: np.random.Generator, mapping: dict, size: int) -> np.ndarray:
    """Return ``size`` draws from ``mapping`` (label -> probability)."""
    labels = list(mapping.keys())
    probs = np.array(list(mapping.values()), dtype=float)
    probs = probs / probs.sum()
    return rng.choice(labels, size=size, p=probs)


def _clip_lognormal(rng: np.random.Generator,
                    mu: float, sigma: float,
                    low: float, high: float,
                    size: int) -> np.ndarray:
    """Draw log-normal values clipped to ``[low, high]``."""
    values = rng.lognormal(mean=mu, sigma=sigma, size=size)
    return np.clip(values, low, high)


def _sql_str(value) -> str:
    """SQL-escape a python value (string / number / date / None)."""
    if value is None or (isinstance(value, float) and np.isnan(value)):
        return "NULL"
    if isinstance(value, (int, np.integer)):
        return str(int(value))
    if isinstance(value, (float, np.floating)):
        return f"{float(value):.4f}" if abs(float(value)) < 1 else f"{float(value):.2f}"
    if isinstance(value, (date,)):
        return f"DATE '{value.isoformat()}'"
    text = str(value).replace("'", "''")
    return f"'{text}'"


def _write_insert(path: str, table: str, columns: list[str],
                  rows: Iterable[Iterable]) -> None:
    """Write an INSERT-per-row script (Oracle compatible).

    Uses a final COMMIT and a transactional batch every 500 rows.
    """
    col_list = ", ".join(columns)
    with open(path, "w", encoding="utf-8") as handle:
        handle.write(f"-- Auto-generated by generate_portfolio.py (seed={SEED})\n")
        handle.write("SET DEFINE OFF;\n")
        handle.write("SET FEEDBACK OFF;\n\n")
        for idx, row in enumerate(rows, start=1):
            values = ", ".join(_sql_str(v) for v in row)
            handle.write(
                f"INSERT INTO {table} ({col_list}) VALUES ({values});\n"
            )
            if idx % 500 == 0:
                handle.write("COMMIT;\n")
        handle.write("COMMIT;\n")
    logger.info("Wrote %s", path)


# --------------------------------------------------------------------------- #
# Counterparties                                                               #
# --------------------------------------------------------------------------- #

def generate_counterparties(ctx: GeneratorContext) -> pd.DataFrame:
    """Generate the COUNTERPARTIES dataframe."""
    rng = ctx.rng
    nb = NB_COUNTERPARTIES

    types = _weighted_choice(rng, COUNTERPARTY_TYPE_MIX, nb)
    ratings = _weighted_choice(rng, RATING_MIX, nb)
    countries = _weighted_choice(rng, COUNTRY_MIX, nb)
    sectors = rng.choice(SECTOR_CODES, size=nb)

    turnover = np.full(nb, np.nan)
    for cp_type, params in TURNOVER_PARAMS.items():
        if params is None:
            continue
        mask = types == cp_type
        if mask.any():
            turnover[mask] = rng.lognormal(
                mean=params["mu"], sigma=params["sigma"], size=mask.sum()
            )

    default_flag = (ratings == "D").astype(int)
    default_date = np.where(
        default_flag == 1,
        [date.today() - timedelta(days=int(d)) for d in rng.integers(1, 365, nb)],
        [None] * nb,
    )

    today = date.today()
    creation_dates = [
        today - timedelta(days=int(d)) for d in rng.integers(30, 2000, nb)
    ]

    df = pd.DataFrame({
        "COUNTERPARTY_ID":   np.arange(1, nb + 1),
        "COUNTERPARTY_TYPE": types,
        "COUNTRY_CODE":      countries,
        "SECTOR_CODE":       sectors,
        "INTERNAL_RATING":   ratings,
        "ANNUAL_TURNOVER":   turnover.round(2),
        "DEFAULT_FLAG":      default_flag,
        "DEFAULT_DATE":      default_date,
        "CREATION_DATE":     creation_dates,
    })
    logger.info("Generated %d counterparties", len(df))
    return df


# --------------------------------------------------------------------------- #
# Contracts                                                                    #
# --------------------------------------------------------------------------- #

def generate_contracts(ctx: GeneratorContext,
                       counterparties: pd.DataFrame) -> pd.DataFrame:
    """Generate the CONTRACTS dataframe (5 000 rows)."""
    rng = ctx.rng
    nb = NB_CONTRACTS

    cp_idx = rng.integers(0, len(counterparties), size=nb)
    cp = counterparties.iloc[cp_idx].reset_index(drop=True)

    products = _weighted_choice(rng, PRODUCT_TYPE_MIX, nb)
    assets = _weighted_choice(rng, ASSET_CLASS_MIX, nb)

    original = np.empty(nb)
    for cp_type, params in BALANCE_PARAMS.items():
        mask = cp["COUNTERPARTY_TYPE"].values == cp_type
        if mask.any():
            original[mask] = _clip_lognormal(
                rng, params["mu"], params["sigma"],
                params["low"], params["high"], mask.sum(),
            )

    progress = rng.uniform(0.05, 0.95, nb)
    outstanding = original * progress

    residual = original * rng.uniform(0.05, 0.25, nb)
    residual = np.where(products == "FINANCE_LEASE", 0.0, residual)

    today = date.today()
    durations_months = rng.integers(24, 73, nb)
    start_dates = [
        today - timedelta(days=int(d)) for d in rng.integers(30, 1800, nb)
    ]
    maturity_dates = [
        s + timedelta(days=int(m) * 30) for s, m in zip(start_dates, durations_months)
    ]
    remaining_months = [
        max(0, int((md - today).days // 30)) for md in maturity_dates
    ]

    statuses = np.where(cp["DEFAULT_FLAG"].values == 1, "DEFAULT", "ACTIVE")
    watch_mask = (statuses == "ACTIVE") & (rng.uniform(0, 1, nb) < 0.05)
    statuses = np.where(watch_mask, "WATCHLIST", statuses)
    closed_mask = (statuses == "ACTIVE") & (rng.uniform(0, 1, nb) < 0.04)
    statuses = np.where(closed_mask, "CLOSED", statuses)

    provision_pct = np.where(
        statuses == "DEFAULT",
        rng.uniform(0.30, 0.80, nb),
        np.where(statuses == "WATCHLIST",
                 rng.uniform(0.05, 0.15, nb),
                 rng.uniform(0.00, 0.02, nb)),
    )
    provisions = (outstanding * provision_pct).round(2)

    df = pd.DataFrame({
        "CONTRACT_ID":         np.arange(1, nb + 1),
        "COUNTERPARTY_ID":     cp["COUNTERPARTY_ID"].values,
        "PRODUCT_TYPE":        products,
        "ASSET_CLASS":         assets,
        "ORIGINAL_AMOUNT":     original.round(2),
        "OUTSTANDING_BALANCE": outstanding.round(2),
        "RESIDUAL_VALUE":      residual.round(2),
        "START_DATE":          start_dates,
        "MATURITY_DATE":       maturity_dates,
        "REMAINING_MONTHS":    remaining_months,
        "CURRENCY":            ["EUR"] * nb,
        "STATUS":              statuses,
        "PROVISION_AMOUNT":    provisions,
    })
    logger.info("Generated %d contracts", len(df))
    return df


# --------------------------------------------------------------------------- #
# Collaterals                                                                  #
# --------------------------------------------------------------------------- #

def generate_collaterals(ctx: GeneratorContext,
                         contracts: pd.DataFrame) -> pd.DataFrame:
    """Generate one COLLATERAL row per contract."""
    rng = ctx.rng
    nb = len(contracts)

    types = _weighted_choice(rng, COLLATERAL_TYPE_PROB, nb)
    haircuts = np.array([DEFAULT_HAIRCUTS[t] for t in types])

    coverage = rng.uniform(0.5, 1.2, nb)
    values = contracts["OUTSTANDING_BALANCE"].values * coverage
    values = np.where(types == "NONE", 0.0, values)

    eligible = np.where(types == "NONE", 0, 1)

    today = date.today()
    dates = [today - timedelta(days=int(d)) for d in rng.integers(1, 365, nb)]

    df = pd.DataFrame({
        "COLLATERAL_ID":    np.arange(1, nb + 1),
        "CONTRACT_ID":      contracts["CONTRACT_ID"].values,
        "COLLATERAL_TYPE":  types,
        "COLLATERAL_VALUE": values.round(2),
        "COLLATERAL_DATE":  dates,
        "HAIRCUT_PCT":      haircuts.round(4),
        "ELIGIBLE_FLAG":    eligible,
    })
    logger.info("Generated %d collaterals", len(df))
    return df


# --------------------------------------------------------------------------- #
# Regulatory parameters (seed)                                                 #
# --------------------------------------------------------------------------- #

def generate_regulatory_parameters() -> pd.DataFrame:
    """Seed the REGULATORY_PARAMETERS table with CRR2 standard-approach values.

    The pipeline looks parameters up by (ASSET_CLASS, COUNTERPARTY_TYPE,
    INTERNAL_RATING). NULL acts as a wildcard.
    """
    pd_by_rating = {
        "AAA": 0.0003,
        "AA":  0.0005,
        "A":   0.0010,
        "BBB": 0.0025,
        "BB":  0.0100,
        "B":   0.0500,
        "CCC": 0.1500,
        "D":   1.0000,
    }

    rw_by_type = {
        "RETAIL":    0.75,
        "SME":       0.85,
        "CORPORATE": 1.00,
    }

    rows = []
    param_id = 1
    today = date.today()
    for cp_type, rw in rw_by_type.items():
        for rating, pd_floor in pd_by_rating.items():
            rows.append({
                "PARAM_ID":          param_id,
                "ASSET_CLASS":       None,
                "COUNTERPARTY_TYPE": cp_type,
                "INTERNAL_RATING":   rating,
                "PD_FLOOR":          pd_floor,
                "LGD_SECURED":       0.35,
                "LGD_UNSECURED":     0.45,
                "RISK_WEIGHT":       rw,
                "CCF":               1.00 if cp_type == "CORPORATE" else 0.50,
                "EFFECTIVE_DATE":    today,
            })
            param_id += 1

    # Asset-class overrides used when a vehicle collateral covers >= 50% LTV.
    rows.append({
        "PARAM_ID":          param_id,
        "ASSET_CLASS":       "PASSENGER_CAR",
        "COUNTERPARTY_TYPE": None,
        "INTERNAL_RATING":   None,
        "PD_FLOOR":          0.0003,
        "LGD_SECURED":       0.30,
        "LGD_UNSECURED":     0.45,
        "RISK_WEIGHT":       0.50,
        "CCF":               1.00,
        "EFFECTIVE_DATE":    today,
    })
    df = pd.DataFrame(rows)
    logger.info("Generated %d regulatory parameter rows", len(df))
    return df


# --------------------------------------------------------------------------- #
# Main                                                                         #
# --------------------------------------------------------------------------- #

def build_dataframes() -> dict[str, pd.DataFrame]:
    """Build the four core dataframes (used by compute_metrics.py)."""
    Faker.seed(SEED)
    ctx = GeneratorContext(rng=np.random.default_rng(SEED), fake=Faker("fr_FR"))
    counterparties = generate_counterparties(ctx)
    contracts = generate_contracts(ctx, counterparties)
    collaterals = generate_collaterals(ctx, contracts)
    params = generate_regulatory_parameters()
    return {
        "counterparties": counterparties,
        "contracts": contracts,
        "collaterals": collaterals,
        "parameters": params,
    }


def main() -> None:
    """Generate SQL INSERT scripts + CSV exports for the synthetic portfolio."""
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    frames = build_dataframes()

    table_map = {
        "counterparties": "COUNTERPARTIES",
        "contracts":      "CONTRACTS",
        "collaterals":    "COLLATERALS",
        "parameters":     "REGULATORY_PARAMETERS",
    }

    for key, table in table_map.items():
        df = frames[key]
        _write_insert(
            os.path.join(OUTPUT_DIR, f"{key}_data.sql"),
            table,
            list(df.columns),
            df.itertuples(index=False, name=None),
        )
        df.to_csv(os.path.join(OUTPUT_DIR, f"{key}.csv"), index=False)
        logger.info("Wrote %s.csv", key)

    logger.info("Done. Files written to %s", OUTPUT_DIR)


if __name__ == "__main__":
    main()
